In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(data={'A': [3, 2, 1], 'B': [6,5,4], 'C': [9, 8, 7]}, 
                  index=['i', 'j', 'k'])

In [3]:
print("Pandas DataFrame: ")
print(df)

Pandas DataFrame: 
   A  B  C
i  3  6  9
j  2  5  8
k  1  4  7


In [4]:
np_arr = df.to_numpy()
print("Pandas DataFrame to NumPy array: ")
print(np_arr)

Pandas DataFrame to NumPy array: 
[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [5]:
arr = df[['B', 'C']].to_numpy()
print("Convert B and C columns of Pandas DataFrame to NumPy Array: ")
print (arr)

Convert B and C columns of Pandas DataFrame to NumPy Array: 
[[6 9]
 [5 8]
 [4 7]]


#### CREATING A LIST

In [6]:
a_list=list("abcdefg")
numpy_array=np.arange(1,10)
dictionary={"A":0,"B":1,"C":2,"D":3,"E":5}

#### COMBINING MANY SERIES

In [7]:
series1=pd.Series(a_list)
print(series1)

0    a
1    b
2    c
3    d
4    e
5    f
6    g
dtype: object


In [8]:
series2=pd.Series(numpy_array)
print(series2)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


In [9]:
series3=pd.Series(dictionary)
print(series3)

A    0
B    1
C    2
D    3
E    5
dtype: int64


In [10]:
ser1=pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser2=pd.Series(np.arange(26))

In [11]:
ser_df=pd.DataFrame(ser1,ser2).reset_index() #ser2 is the index and ser1 is the data

In [12]:
ser_df.head()

index  0
0      0  a
1      1  b
2      2  c
3      3  d
4      4  e

In [13]:
ser_df=pd.DataFrame({"col1":ser1,"col2":ser2})

In [14]:
ser_df.head()

col1  col2
0    a     0
1    b     1
2    c     2
3    d     3
4    e     4

In [15]:
ser_df=pd.concat([ser1,ser2],axis=1)

In [16]:
ser_df.head()

0  1
0  a  0
1  b  1
2  c  2
3  d  3
4  e  4

In [17]:
import pandas as pd
import numpy as np

dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
df = pd.DataFrame(dict)
df.fillna(0)

First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0